AWSTemplateFormatVersion: '2010-09-09'
Description: Auth0 Demo Custom Provider 
Resources:
  Client:
    Type: Custom::Auth0Client
    Properties:
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:cfn-auth0-provider'
      OutputParameters:
        - Name: /auth0-resources/client/id
          Description: OAuth client id
          Path: client_id
        - Name: /auth0-resources/client/secret
          Path: client_secret
          Description: OAuth client secret

      Value: 
        name: cfn-auth0-petsstore-client
        description: Sample Auth0 Client
        app_type: non_interactive
        allowed_origins:
          - 'http://localhost:3000'
        callbacks:
          - 'http://localhost:3000/consumer-api/v1/callback'
        jwt_configuration:
          lifetime_in_seconds: 3600
          alg: RS256
        grant_types:
          - authorization_code
          - 'http://auth0.com/oauth/grant-type/password-realm'
          - implicit
          - password
          - refresh_token
        token_endpoint_auth_method: none
        is_token_endpoint_ip_header_trusted: false
        sso_disabled: false
        oidc_conformant: true
        cross_origin_auth: false
        sso: false
        custom_login_page_on: true
        allowed_clients: []
        is_first_party: true
        allowed_logout_urls: []


  ClientGrant:
    Type: Custom::Auth0ClientGrant
    DependsOn: [ Client, API ]
    Properties:
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:cfn-auth0-provider'
      Value: 
        client_id: !Ref Client
        audience: 'https://github.com/binxio/cfn-auth0-provider/petstore'
        scope:
          - get:pets

  API:
    Type: Custom::Auth0ResourceServer
    Properties:
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:cfn-auth0-provider'
      Value: 
        name: cfn-auth0-petstore-api
        identifier: 'https://github.com/binxio/cfn-auth0-provider/petstore'
        allow_offline_access: false
        skip_consent_for_verifiable_first_party_clients: true
        token_lifetime: 900
        token_lifetime_for_web: 900
        signing_alg: RS256
        scopes:
          - {value: 'create:pets', description: 'add pets'}
          - {value: 'update:pets', description: 'update pets'}
          - {value: 'get:pets', description: 'get pets'}
          - {value: 'delete:pets', description: 'delete pets'}
          - {value: 'list:pets', description: 'list all pets'}

  Rule:
    Type: Custom::Auth0Rule
    Properties:
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:cfn-auth0-provider'
      Value: 
        name: 'cfn-auth0-petstore-rule'
        enabled: false
        script: |
          function (user, context, callback) {
            // do want you need to do here
            callback(null, user, context);
          }

Outputs:
  ClientId:
    Description: The client id of the Auth0 Client
    Value: !GetAtt 'Client.ClientId'

  ClientSecret:
    Description: The secret key of the client
    Value: !GetAtt 'Client.ClientSecret'
